import {materialPatterns,materialKey} from './material-graphics.js?v=2026-09-30';
import {MATERIALS,material,WALL_PRESETS,presetLayers,layersOf,wallQuantities,materialTotals} from './materials.js?v=2026-09-30';
import {CATALOG,uid,rad,dist,wallLength,wallPoint,wallFrame,projectOnWall,rect,bodyPolygon,frontZone,wallPieces,wallPolygon,wallLayerPolygons,doorGeometry,makeFurniture,makeWall,blankPlan,rectangularPlan,demoPlan,validatePlan,analyse,nearestFrontGap,snapFurniture} from './model.js?v=2026-09-30';
const $=id=>document.getElementById(id),clone=structuredClone,STORAGE='robion_rooms_v1';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let project=demoPlan(),selected=null,tool='select',category='Wszystko',precision=1,magnet=true,gridStep=5,showDimensions=true,showZones=true,mode='2d',view3d=null,issues=[],pendingPoint=null,previewPoint=null,drag=null,edit=null,tab='properties',stored=true;
const history=[],future=[];let view={x:-90,y:-90,w:980,h:800},fitWidth=980;
try{const saved=localStorage.getItem(STORAGE);if(saved)project=validatePlan(JSON.parse(saved));}catch(e){setTimeout(()=>toast('Nie udało się odczytać zapisu lokalnego. Możesz wczytać plik projektu.',true),300);}
function toast(message,error=false){$('toast').textContent=message;$('toast').className='visible'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').className='',4500);}
const fmt=n=>Number(n).toLocaleString('pl-PL',{minimumFractionDigits:precision,maximumFractionDigits:precision});
const num=n=>Number(n).toFixed(precision);
function entity(id=selected,p=project){for(const key of ['furniture','walls','openings','labels','measurements']){const value=p[key].find(v=>v.id===id);if(value)return {key,value};}return null;}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(project));stored=true;$('save-state').textContent='Zapisano na tym urządzeniu';}catch{stored=false;$('save-state').textContent='Zapis lokalny niedostępny · pobierz plik';}}
function push(before){history.push(clone(before));if(history.length>80)history.shift();future.length=0;}
function commit(next,id=selected){finishEdit();try{const valid=validatePlan(next);if(JSON.stringify(project)===JSON.stringify(valid))return;push(project);project=valid;selected=id;persist();render();}catch(e){toast(e.message,true);}}
function finishEdit(){if(!edit)return;if(JSON.stringify(edit.before)!==JSON.stringify(project)){push(edit.before);persist();}edit=null;updateHistory();}
function cancelGesture(){if(drag?.before)project=drag.before;if(edit)project=edit.before;edit=null;drag=null;pendingPoint=null;previewPoint=null;render();}
function undo(){finishEdit();cancelGesture();if(!history.length)return;future.push(clone(project));project=history.pop();if(!entity())selected=null;persist();render();}
function redo(){finishEdit();cancelGesture();if(!future.length)return;history.push(clone(project));project=future.pop();if(!entity())selected=null;persist();render();}
function updateHistory(){$('undo').disabled=!history.length&&!edit;$('redo').disabled=!future.length;}
function select(id){finishEdit();selected=id;tool='select';pendingPoint=null;previewPoint=null;syncTools();render();}
function setTool(next){finishEdit();if(mode!=='2d')setView('2d');tool=next;pendingPoint=null;previewPoint=null;syncTools();draw();if(innerWidth<700)$('library').classList.remove('open');}
function syncTools(){document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active','furniture:'+b.dataset.kind===tool));$('select-tool').classList.toggle('active',tool==='select');
 const hints={select:'Przeciągnij element lub uchwyt · kółko: zoom · prawy przycisk / spacja: przesuń plan',wall:'Kliknij początek i koniec ściany · Shift: prostopadle · Esc: anuluj',room:'Kliknij dwa przeciwległe narożniki obrysu · wymiary między osiami ścian',door:'Kliknij ścianę w miejscu drzwi. Kierunek otwierania zmienisz we właściwościach.',window:'Kliknij ścianę w miejscu okna.',label:'Kliknij miejsce nazwy pomieszczenia, a potem wpisz własną nazwę.',measure:'Kliknij dwa punkty, aby zmierzyć odległość w centymetrach.'};
 $('draw-hint').textContent=mode==='3d'?'Przeciągnij: obrót · kółko: zoom · prawy przycisk: przesuń · edycja położenia w rzucie 2D':tool.startsWith('furniture:')?'Kliknij na planie, aby wstawić wyposażenie. Następnie przeciągnij je lub zmień wymiary.':hints[tool];
 $('plan').style.cursor=tool==='select'?'default':'crosshair';
}
function planBounds(){const pts=[{x:0,y:0},{x:project.floor.width,y:project.floor.depth},...project.walls.flatMap(w=>[w.a,w.b]),...project.furniture.flatMap(bodyPolygon)];return {minX:Math.min(...pts.map(p=>p.x)),minY:Math.min(...pts.map(p=>p.y)),maxX:Math.max(...pts.map(p=>p.x)),maxY:Math.max(...pts.map(p=>p.y))};}
function fit(){if(mode==='3d'){view3d?.fit();return;}const b=planBounds(),r=$('stage').getBoundingClientRect(),ratio=r.width/Math.max(r.height,1),w=b.maxX-b.minX+180,h=b.maxY-b.minY+180;const ww=Math.max(w,h*ratio),hh=ww/ratio;view={x:(b.minX+b.maxX-ww)/2,y:(b.minY+b.maxY-hh)/2,w:ww,h:hh};fitWidth=ww;applyView();}
function applyView(){$('plan').setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);$('zoom-value').textContent=Math.round(fitWidth/view.w*100)+'%';}
function zoom(factor,center){if(mode==='3d'){view3d?.zoom(factor);return;}const p=center||{x:view.x+view.w/2,y:view.y+view.h/2},w=Math.min(30000,Math.max(120,view.w*factor)),f=w/view.w;view={x:p.x-(p.x-view.x)*f,y:p.y-(p.y-view.y)*f,w,h:view.h*f};applyView();}
function point(e){const svg=$('plan'),p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function snapPoint(p,shift=false){let v={x:Math.round(p.x/gridStep)*gridStep,y:Math.round(p.y/gridStep)*gridStep};if(magnet){let best=10*view.w/Math.max(1,$('stage').clientWidth);for(const q of project.walls.flatMap(w=>[w.a,w.b])){const d=dist(v,q);if(d<best){v={...q};best=d;}}}if(shift&&pendingPoint){if(Math.abs(v.x-pendingPoint.x)>Math.abs(v.y-pendingPoint.y))v.y=pendingPoint.y;else v.x=pendingPoint.x;}return v;}
const pts=poly=>poly.map(p=>`${p.x},${p.y}`).join(' ');
const text=(x,y,s,size=11,color='#748996',extra='')=>`<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" font-size="${size}" fill="${color}" ${extra}>${esc(s)}</text>`;
function dimension(a,b,label,color='#9cabb3',offset=0){const l=dist(a,b);if(l<.1)return '';const nx=-(b.y-a.y)/l,ny=(b.x-a.x)/l,p={x:a.x+nx*offset,y:a.y+ny*offset},q={x:b.x+nx*offset,y:b.y+ny*offset},mx=(p.x+q.x)/2,my=(p.y+q.y)/2;let angle=Math.atan2(q.y-p.y,q.x-p.x)*180/Math.PI;if(angle>90||angle<-90)angle+=180;return `<g pointer-events="none"><path d="M${a.x},${a.y}L${p.x+nx*5},${p.y+ny*5} M${b.x},${b.y}L${q.x+nx*5},${q.y+ny*5} M${p.x},${p.y}L${q.x},${q.y} M${p.x-nx*4},${p.y-ny*4}L${p.x+nx*4},${p.y+ny*4} M${q.x-nx*4},${q.y-ny*4}L${q.x+nx*4},${q.y+ny*4}" fill="none" stroke="${color}" stroke-width=".8"/><g transform="rotate(${angle},${mx},${my})"><rect x="${mx-String(label).length*3.3-4}" y="${my-8}" width="${String(label).length*6.6+8}" height="16" rx="3" fill="#f7faf9"/>${text(mx,my,label,11,color)}</g></g>`;}
function furnitureSymbol(f){const w=f.w,d=f.d,k=f.kind,stroke='#6c858e',fill='#ffffff7a';let s='';const r=(x,y,w,h,rx=2)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}" fill="${fill}" stroke="${stroke}" stroke-width="1"/>`;const line=(x1,y1,x2,y2)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="${stroke}" stroke-width="1" fill="none"/>`;
 if(k==='sofa'){s+=r(-w/2+9,-d/2+8,w-18,15,4)+r(-w/2+3,-d/2+8,13,d-13,4)+r(w/2-16,-d/2+8,13,d-13,4);for(let i=0;i<3;i++)s+=r(-w/2+18+i*(w-36)/3,-d/2+28,(w-36)/3-2,d-34,5);}
 else if(k==='bed'){s+=r(-w/2+5,-d/2+7,w-10,d-14,4)+r(-w/2+11,-d/2+15,w/2-16,32,5)+r(5,-d/2+15,w/2-16,32,5)+line(-w/2+5,-d/2+58,w/2-5,-d/2+58);}
 else if(k==='sink'||k==='basin'){s+=r(-w*.32,-d*.32,w*.64,d*.64,Math.min(8,d/4))+`<circle cx="0" cy="0" r="3" fill="${stroke}"/>`+line(0,-d/2+3,0,-d/2+15);}
 else if(k==='wc'){s+=r(-w/2+3,-d/2+3,w-6,d*.23,3)+`<ellipse cx="0" cy="${d*.12}" rx="${w*.4}" ry="${d*.32}" fill="${fill}" stroke="${stroke}"/><ellipse cx="0" cy="${d*.1}" rx="${w*.27}" ry="${d*.23}" fill="none" stroke="${stroke}"/>`;}
 else if(k==='shower'){s+=r(-w/2+4,-d/2+4,w-8,d-8,2)+`<circle cx="0" cy="0" r="4" fill="${stroke}"/>`+line(-w/2+4,-d/2+4,w/2-4,d/2-4)+line(w/2-4,-d/2+4,-w/2+4,d/2-4);}
 else if(k==='bath'){s+=r(-w/2+7,-d/2+7,w-14,d-14,Math.min(w,d)/3)+`<circle cx="${-w*.3}" cy="0" r="3" fill="${stroke}"/>`;}
 else if(k==='hob'){for(const x of [-w*.23,w*.23])for(const y of [-d*.23,d*.23])s+=`<circle cx="${x}" cy="${y}" r="${Math.min(w,d)*.15}" fill="none" stroke="${stroke}" stroke-width="1.3"/>`;}
 else if(k==='washer'){s+=`<circle cx="0" cy="0" r="${Math.min(w,d)*.29}" fill="${fill}" stroke="${stroke}"/>`+line(-w/2+3,-d/2+9,w/2-3,-d/2+9);}
 else if(k==='table'||k==='desk'){s+=r(-w/2+4,-d/2+4,w-8,d-8,3);}
 else if(k==='chair'){s+=r(-w/2+4,-d/2+4,w-8,9,3)+r(-w/2+4,-d/2+15,w-8,d-19,4);}
 else {s+=line(-w/2+3,d/2-7,w/2-3,d/2-7);if(w>90)s+=line(0,-d/2+3,0,d/2-7);s+=line(-8,d/2-12,8,d/2-12);if(k==='fridge')s+=text(0,0,'F',14,stroke);if(k==='dishwasher')s+=text(0,0,'Z',14,stroke);}
 return s;
}
function furnitureSvg(f,forIcon=false){const selectedHere=f.id===selected&&!forIcon,err=issues.some(i=>i.level==='error'&&i.ids.includes(f.id));return `<g ${forIcon?'':`data-id="${esc(f.id)}"`} transform="translate(${f.x},${f.y}) rotate(${f.angle})"><rect x="${-f.w/2}" y="${-f.d/2}" width="${f.w}" height="${f.d}" rx="${Math.min(4,f.w/10)}" fill="${err&&!forIcon?'#f1ccc0':f.color}" stroke="${selectedHere?'#bb8530':err&&!forIcon?'#ce806d':'#8da0a4'}" stroke-width="${selectedHere?2.5:1.1}"/>${furnitureSymbol(f)}<path d="M-4 ${f.d/2-1}l4 -5 4 5" fill="#6b8790"/>${!forIcon&&f.w>=70?text(0,0,f.name.length>21?f.name.slice(0,20)+'…':f.name,10,'#425e68','paint-order="stroke" stroke="#ffffffaa" stroke-width="3"'):''}</g>`;}
function draw(){
 let s=`<defs>${materialPatterns()}</defs><rect x="${view.x-10000}" y="${view.y-10000}" width="${view.w+20000}" height="${view.h+20000}" fill="url(#grid)" opacity=".55"/><rect x="0" y="0" width="${project.floor.width}" height="${project.floor.depth}" fill="#faf8f1" stroke="#e3e5dc" stroke-width="1"/>`;
 if(showZones)for(const f of project.furniture)if(f.clear>0){const bad=issues.some(i=>i.type==='clearance'&&i.ids[0]===f.id);s+=`<polygon points="${pts(frontZone(f))}" fill="${bad?'#efd49d':'#bddbca'}" fill-opacity=".25" stroke="${bad?'#d3b577':'#a7c2b4'}" stroke-width=".8" stroke-dasharray="4 4" pointer-events="none"/>`;}
 for(const l of project.labels)s+=`<g data-id="${esc(l.id)}">${text(l.x,l.y,l.name,12,l.id===selected?'#b17f37':'#97a6a8','letter-spacing="2"')}${l.id===selected?`<circle cx="${l.x}" cy="${l.y+17}" r="4" fill="#eabf7d"/>`:''}</g>`;
 for(const w of project.walls){const selectedHere=w.id===selected;
  s+=`<g data-id="${esc(w.id)}"><path d="M${w.a.x},${w.a.y}L${w.b.x},${w.b.y}" stroke="transparent" stroke-width="${Math.max(w.thickness,12)}"/>`;
  for(const part of wallPieces(project,w))if(part.z<1){for(const layer of wallLayerPolygons(project,w,part.start,part.end))s+=`<polygon points="${pts(layer.polygon)}" fill="url(#mat-${layer.material})" stroke="#819096" stroke-width=".35"><title>${material(layer.material).name} · ${fmt(layer.thickness)} cm</title></polygon>`;s+=`<polygon points="${pts(wallPolygon(w,part.start,part.end,project))}" fill="none" stroke="${selectedHere?'#b78a40':'#687e87'}" stroke-width="${selectedHere?2:.8}" pointer-events="none"/>`;}
  s+='</g>';
 }
 for(const o of project.openings){const w=project.walls.find(w=>w.id===o.wall),{l,u}=wallFrame(w),a=wallPoint(w,o.t-o.width/2/l),b=wallPoint(w,o.t+o.width/2/l),c=wallPoint(w,o.t),err=issues.some(i=>i.type==='door'&&i.ids[0]===o.id),color=o.id===selected?'#b68434':err?'#c97a65':'#83a5a6';
  s+=`<g data-id="${esc(o.id)}"><path d="M${a.x},${a.y}L${b.x},${b.y}" stroke="${o.kind==='window'?'#d3e6e9':'#faf8f1'}" stroke-width="${w.thickness+1}"/>`;
  if(o.kind==='door'){const d=doorGeometry(project,o);s+=`<polygon points="${pts(d.polygon)}" fill="${err?'#f0b7a5':'#bcd5ca'}" fill-opacity="${showZones?.28:.09}"/><polyline points="${pts(d.polygon.slice(1))}" fill="none" stroke="${color}" stroke-width="1.1" stroke-dasharray="4 3"/><path d="M${d.hinge.x},${d.hinge.y}L${d.open.x},${d.open.y}" stroke="${color}" stroke-width="3"/><circle cx="${d.hinge.x}" cy="${d.hinge.y}" r="2.5" fill="${color}"/>`;
  }else{s+=`<path d="M${a.x},${a.y}L${b.x},${b.y}" stroke="${color}" stroke-width="3"/><path d="M${c.x-u.y*w.thickness/2},${c.y+u.x*w.thickness/2}L${c.x+u.y*w.thickness/2},${c.y-u.x*w.thickness/2}" stroke="${color}" stroke-width="1"/>`;}
  s+=`<circle cx="${c.x}" cy="${c.y}" r="${o.id===selected?5:2}" fill="${color}"/></g>`;
 }
 for(const f of project.furniture)s+=furnitureSvg(f);
 if(showDimensions){const w=project.floor.width,d=project.floor.depth;s+=dimension({x:0,y:0},{x:w,y:0},fmt(w)+' cm','#879da7',-42)+dimension({x:0,y:d},{x:0,y:0},fmt(d)+' cm','#879da7',-42);}
 for(const m of project.measurements)s+=`<g data-id="${esc(m.id)}"><path d="M${m.a.x},${m.a.y}L${m.b.x},${m.b.y}" stroke="transparent" stroke-width="12"/>${dimension(m.a,m.b,fmt(dist(m.a,m.b))+' cm',m.id===selected?'#bd8838':'#618a9e')}</g>`;
 const chosen=entity();if(chosen){const e=chosen.value;
  if(chosen.key==='furniture'){
   if(showDimensions){const c=bodyPolygon(e);s+=dimension(c[0],c[1],fmt(e.w),'#b18a4c',-14)+dimension(c[1],c[2],fmt(e.d),'#b18a4c',-14);}
   const off=e.d/2+29,c=Math.cos(rad(e.angle)),sn=Math.sin(rad(e.angle)),h={x:e.x+sn*off,y:e.y-c*off};s+=`<g><path d="M${e.x},${e.y}L${h.x},${h.y}" stroke="#ba8b43" stroke-width="1" stroke-dasharray="3 3" pointer-events="none"/><circle data-id="${esc(e.id)}" data-handle="rotate" cx="${h.x}" cy="${h.y}" r="8" fill="#fff" stroke="#be8d42" stroke-width="1.5"/>${text(h.x,h.y,'↻',11,'#a87a36','pointer-events="none"')}</g>`;
  }else if(['walls','measurements'].includes(chosen.key)){for(const end of ['a','b'])s+=`<circle data-id="${esc(e.id)}" data-handle="${end}" cx="${e[end].x}" cy="${e[end].y}" r="6" fill="#fff8e8" stroke="#bc8b43" stroke-width="1.5"/>`;if(chosen.key==='walls')s+=dimension(e.a,e.b,fmt(wallLength(e))+' cm','#b18a4c',-22);}
 }
 if(pendingPoint&&previewPoint){if(tool==='room'){s+=`<rect x="${Math.min(pendingPoint.x,previewPoint.x)}" y="${Math.min(pendingPoint.y,previewPoint.y)}" width="${Math.abs(previewPoint.x-pendingPoint.x)}" height="${Math.abs(previewPoint.y-pendingPoint.y)}" fill="#edc68122" stroke="#b88a43" stroke-width="2" stroke-dasharray="6 4"/>`;}else{s+=`<path d="M${pendingPoint.x},${pendingPoint.y}L${previewPoint.x},${previewPoint.y}" stroke="#c29349" stroke-width="${tool==='wall'?12:2}" stroke-opacity=".5"/>`;}s+=dimension(pendingPoint,previewPoint,fmt(dist(pendingPoint,previewPoint))+' cm','#a27a37',-15);}
 $('drawing').innerHTML=s;applyView();
}
function render(keepEditor=false){issues=analyse(project);$('project-name').value=project.name;$('canvas-title').textContent=project.name.toUpperCase();$('area').textContent=`Obszar: ${fmt(project.floor.width*project.floor.depth/10000)} m²`;$('issue-count').textContent=issues.length;$('object-count').textContent=project.walls.length+project.furniture.length+project.openings.length+project.labels.length+project.measurements.length;
 draw();if(mode==='3d'&&view3d)view3d.update(project,selected,issues,{lowWalls:$('low-walls').checked,zones:showZones});if(!keepEditor)renderEditor();renderIssues();renderObjects();updateHistory();syncTools();
}
function renderCatalog(){const q=$('catalog-search').value.toLowerCase();$('catalog').innerHTML=CATALOG.filter(c=>(category==='Wszystko'||c.group===category)&&c.name.toLowerCase().includes(q)).map(c=>{const f={...makeFurniture(c.kind,0,0),id:'icon',w:c.w,d:c.d};return `<button data-kind="${c.kind}" aria-label="Wstaw: ${esc(c.name)}"><svg viewBox="${-c.w/2-5} ${-c.d/2-5} ${c.w+10} ${c.d+10}" aria-hidden="true">${furnitureSvg(f,true)}</svg><strong>${c.name}</strong><small>${c.w} × ${c.d} cm</small></button>`;}).join('');$('catalog').querySelectorAll('button').forEach(b=>b.onclick=()=>setTool('furniture:'+b.dataset.kind));syncTools();}
function field(label,key,value,opts={}){return `<label class="${opts.wide?'wide':''}">${label}<input name="${key}" aria-label="${label}" type="${opts.type||'number'}" ${opts.type==='text'?'maxlength="100"':opts.type==='color'?'':`step="${10**-precision}" ${opts.min!==undefined?`min="${opts.min}"`:''} ${opts.max!==undefined?`max="${opts.max}"`:''}`} value="${esc(typeof value==='number'?num(value):value)}"></label>`;}
function wallLayerEditor(w){return `<fieldset class="wall-layers"><legend>Materiały i warstwy</legend><p class="hint wide">Kolejność: lewa → prawa strona osi, patrząc od początku A do końca B. Grubość rośnie symetrycznie względem osi.</p><label class="wide">Przykładowy układ<select id="wall-preset"><option value="">Wybierz układ…</option>${WALL_PRESETS.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('')}</select></label>${layersOf(w).map((l,i)=>`<div class="layer-row"><label>Warstwa ${i+1}<select name="layers.${i}.material" aria-label="Materiał warstwy ${i+1}">${MATERIALS.map(m=>`<option value="${m.id}" ${m.id===l.material?'selected':''}>${m.name}</option>`).join('')}</select></label>${field('Grubość warstwy '+(i+1)+' [cm]','layers.'+i+'.thickness',l.thickness,{min:.1,max:100})}<button type="button" data-remove-layer="${i}" aria-label="Usuń warstwę ${i+1}" ${layersOf(w).length===1?'disabled':''}>×</button></div>`).join('')}<button type="button" id="add-layer" class="wide" ${layersOf(w).length>=12?'disabled':''}>＋ Dodaj warstwę</button><button type="button" id="reverse-layers" class="wide">Odwróć kolejność warstw</button><p class="hint wide">Układy są edytowalnymi przykładami. Pustka / ruszt oznacza przestrzeń konstrukcji, nie objętość zakupionego materiału.</p></fieldset>`;}
function bindWallLayers(){if(!$('wall-preset'))return;$('wall-preset').onchange=e=>{if(e.target.value!=='')updateSelected(w=>{w.layers=presetLayers(Number(e.target.value));});};$('add-layer').onclick=()=>updateSelected(w=>{w.layers=[...layersOf(w),{material:'plaster',thickness:1}];});$('reverse-layers').onclick=()=>updateSelected(w=>{w.layers=[...layersOf(w)].reverse();});document.querySelectorAll('[data-remove-layer]').forEach(b=>b.onclick=()=>updateSelected(w=>{w.layers=layersOf(w).filter((_,i)=>i!==Number(b.dataset.removeLayer));}));}
function materialsReport(){return `<details id="material-report"><summary>Materiały wszystkich ścian</summary><p class="hint">Szacunek po osiach: długość × wysokość minus drzwi i okna. Bez korekty narożników, ościeży, zapasu i odpadów. Powierzchnia jest sumowana osobno dla każdej warstwy.</p>${materialTotals(project).map(l=>`<p class="material-total"><b>${material(l.material).name}</b><span>${fmt(l.area)} m² · ${l.volume.toFixed(3)} m³</span></p>`).join('')||'<p>Brak ścian.</p>'}</details>`;}
function renderEditor(){const info=entity();let html='';
 if(!info){html=`<div class="panel-heading"><div><span class="eyebrow">POZIOM 0</span><h2>Obszar planu</h2></div></div><p class="hint">Kliknij wyposażenie, ścianę lub drzwi. Przeciągaj na planie, a dokładne wymiary wpisuj tutaj.</p><form id="property-form" class="field-grid">${field('Szerokość obszaru [cm]','floor.width',project.floor.width,{min:100,max:10000})}${field('Głębokość obszaru [cm]','floor.depth',project.floor.depth,{min:100,max:10000})}</form><p id="field-error" class="error-text"></p><p class="hint">Wymiary obszaru nie skalują mebli ani istniejących ścian. Obrys pokoju rysujesz między osiami ścian; wolny wymiar jest mniejszy o ich grubość.</p>${!project.walls.length?'<button id="outline" class="primary">Dodaj ściany obwodu</button>':''}<div class="editor-summary">${project.furniture.length} elementów wyposażenia<strong>${issues.length} uwag do układu</strong><button id="open-checks">Sprawdź wygodę →</button></div><ul class="help-list"><li>Meble: wybierz z biblioteki i kliknij plan.</li><li>Obrót: uchwyt ↻ nad zaznaczonym meblem.</li><li>Miarka: wybierz dwa punkty przejścia.</li><li>Cofnij: ⌘/Ctrl + Z.</li><li>Każde przeciągnięcie to jeden krok historii.</li></ul>`;
 }else{const {key,value:e}=info;html=`<span class="eyebrow">${{furniture:'WYPOSAŻENIE',walls:'KONSTRUKCJA',openings:'OTWÓR W ŚCIANIE',labels:'OPIS PLANU',measurements:'ODLEGŁOŚĆ'}[key]}</span><h2>${esc(e.name)}</h2><p class="selected-kind">${key==='furniture'?'Wymiary zewnętrzne · cm':key==='walls'?'Początek i koniec osi ściany · cm':key==='openings'?'Położenie wzdłuż osi ściany · cm':'Jednostki: cm'}</p><form id="property-form" class="field-grid">${field('Nazwa','name',e.name,{type:'text',wide:true})}`;
 if(key==='furniture'){html+=field('Szerokość [cm]','w',e.w,{min:5,max:2000})+field('Głębokość [cm]','d',e.d,{min:5,max:2000})+field('Wysokość [cm]','h',e.h,{min:5,max:600})+field('Poziom spodu [cm]','z',e.z,{min:0,max:600})+field('Środek X [cm]','x',e.x)+field('Środek Y [cm]','y',e.y)+field('Obrót [°]','angle',e.angle)+field('Kolor','color',e.color,{type:'color'})+field('Wolne miejsce z przodu [cm]','clear',e.clear,{min:0,max:500,wide:true});}
 if(key==='walls'||key==='measurements'){for(const a of ['a','b'])html+=`<fieldset><legend>${a==='a'?'Początek':'Koniec'}</legend>${field('X '+a.toUpperCase()+' [cm]',a+'.x',e[a].x)}${field('Y '+a.toUpperCase()+' [cm]',a+'.y',e[a].y)}</fieldset>`;if(key==='walls')html+=field('Grubość [cm]','thickness',e.thickness,{min:5,max:100})+field('Wysokość [cm]','height',e.height,{min:50,max:600})+wallLayerEditor(e);}
 if(key==='openings'){const w=project.walls.find(w=>w.id===e.wall);html+=field('Szerokość [cm]','width',e.width,{min:20,max:600})+field('Wysokość [cm]','height',e.height,{min:20,max:600})+field('Środek od początku ściany [cm]','offset',e.t*wallLength(w),{wide:true});if(e.kind==='window')html+=field('Parapet nad podłogą [cm]','sill',e.sill,{min:0,max:500,wide:true});}
 if(key==='labels')html+=field('Położenie X [cm]','x',e.x)+field('Położenie Y [cm]','y',e.y);
 html+='</form><p id="field-error" class="error-text"></p><div id="selection-summary"></div><div class="editor-actions">';
 if(key==='furniture')html+='<button id="rotate">↻ Obróć 90°</button><button id="duplicate">Powiel</button>';
 if(key==='openings'&&e.kind==='door')html+='<button id="door-side">Zmień stronę</button><button id="door-hinge">Zmień zawias</button>';
 html+='<button id="delete" class="danger">Usuń</button></div>';}
 $('properties').innerHTML=html+materialsReport()+materialKey();const form=$('property-form');form.onsubmit=e=>e.preventDefault();form.addEventListener('focusin',e=>{if(e.target.name){finishEdit();edit={before:clone(project),id:selected,input:e.target};}});form.addEventListener('input',e=>liveInput(e.target));form.addEventListener('focusout',e=>{finishEdit();const input=e.target;if(input.getAttribute('aria-invalid')==='true'){const value=entity()?.value||project;const keys=input.name.split('.');const restored=input.name==='offset'?value.t*wallLength(project.walls.find(w=>w.id===value.wall)):keys.reduce((v,k)=>v?.[k],value);input.value=typeof restored==='number'?num(restored):restored;input.removeAttribute('aria-invalid');$('field-error').textContent='Przywrócono ostatnią poprawną wartość.';}});
 bindWallLayers();if(info?.key==='walls'&&info.value.layers)form.elements.thickness.readOnly=true;if($('outline'))$('outline').onclick=()=>{const p=clone(project);p.walls=rectangularPlan(p.floor.width,p.floor.depth).walls;commit(p);};if($('open-checks'))$('open-checks').onclick=()=>showTab('checks');
 if($('delete'))$('delete').onclick=removeSelected;if($('rotate'))$('rotate').onclick=()=>updateSelected(f=>{f.angle=(f.angle+90)%360;});if($('duplicate'))$('duplicate').onclick=duplicate;
 if($('door-side'))$('door-side').onclick=()=>updateSelected(o=>{o.side*=-1;});if($('door-hinge'))$('door-hinge').onclick=()=>updateSelected(o=>{o.hinge*=-1;});updateSummary();
}
function liveInput(input){if(!input.name)return;if(!edit)edit={before:clone(project),id:selected,input};try{const p=clone(project),e=entity(selected,p)?.value||p;let value=input.type==='number'?input.valueAsNumber:input.value;if(input.type==='number'&&(input.value===''||!Number.isFinite(value)))throw Error('Wpisz poprawną liczbę.');if(input.name==='offset'){e.t=value/wallLength(p.walls.find(w=>w.id===e.wall));}else{const keys=input.name.split('.');if(keys[0]==='layers'&&!e.layers)e.layers=layersOf(e);let target=e;for(const key of keys.slice(0,-1))target=target[key];target[keys.at(-1)]=value;}project=validatePlan(p);input.removeAttribute('aria-invalid');$('field-error').textContent='';render(true);updateSummary();if(entity()?.key==='walls'){$('property-form').elements.thickness.value=num(project.walls.find(w=>w.id===selected).thickness);$('property-form').elements.thickness.readOnly=!!entity().value.layers;$('material-report').outerHTML=materialsReport();}}catch(error){input.setAttribute('aria-invalid','true');$('field-error').textContent=error.message;}}
function updateSummary(){const info=entity();if(!$('selection-summary')||!info)return;const {key,value:e}=info;let text='';if(key==='furniture'){const gap=nearestFrontGap(project,e);text=`<div class="editor-summary ${gap+.1<e.clear?'warn':''}">Wolne miejsce z przodu<strong>${gap>=499.9?'≥ 500':fmt(gap)} cm</strong>Ustawiona strefa: ${fmt(e.clear)} cm.<br>Pomiar na całej szerokości frontu do pierwszej przeszkody, do 500 cm.</div>`;}else if(key==='walls'||key==='measurements')text=`<div class="editor-summary">Długość ${key==='walls'?'osi ściany':'pomiaru'}<strong>${fmt(dist(e.a,e.b))} cm</strong></div>`;else if(key==='openings')text='<p class="hint">Przeciągaj punkt otworu wzdłuż ściany. Otwory i ich wysokości są widoczne także w 3D.</p>';
 if(key==='walls'){text+=`<div class="editor-summary">Grubość wszystkich warstw<strong>${fmt(e.thickness)} cm</strong><div class="layer-section" aria-label="Przekrój warstw od lewej do prawej strony osi">${layersOf(e).map(l=>`<span title="${material(l.material).name}: ${fmt(l.thickness)} cm" style="flex:${l.thickness};background:${material(l.material).color}"></span>`).join('')}</div>${wallQuantities(project,e).map(l=>`<div>${material(l.material).name}: ${fmt(l.area)} m² · ${l.volume.toFixed(3)} m³</div>`).join('')}</div>`;} $('selection-summary').innerHTML=text;
}
function renderIssues(){$('issues').innerHTML=issues.length?issues.map((i,n)=>`<button class="issue ${i.level}" data-issue="${n}"><small>${i.level==='error'?'Kolizja / poza planem':'Sprawdź wolne miejsce'}</small>${esc(i.message)}</button>`).join(''):'<div class="checks-ok">✓ Brak wykrytych kolizji i zajętych stref. Sprawdź też przejścia miarką.</div>';$('issues').querySelectorAll('button').forEach(b=>b.onclick=()=>{const issue=issues[Number(b.dataset.issue)];select(issue.ids[0]);showTab('properties');});}
function renderObjects(){$('object-list').innerHTML=['walls','openings','furniture','labels','measurements'].flatMap(key=>project[key].map(e=>`<button data-object="${esc(e.id)}" class="${e.id===selected?'active':''}">${esc(e.name)}<small>${{walls:'ściana',openings:'otwór',furniture:'mebel',labels:'opis',measurements:'miarka'}[key]}</small></button>`)).join('');$('object-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{select(b.dataset.object);showTab('properties');});}
function showTab(next){tab=next;$('properties').hidden=next!=='properties';$('checks').hidden=next!=='checks';$('tab-properties').classList.toggle('active',next==='properties');$('tab-check').classList.toggle('active',next==='checks');$('inspector').classList.add('open');}
function updateSelected(fn){const p=clone(project),info=entity(selected,p);if(info){fn(info.value);commit(p);}}
function removeSelected(){finishEdit();const info=entity();if(!info)return;const p=clone(project);p[info.key]=p[info.key].filter(e=>e.id!==selected);if(info.key==='walls')p.openings=p.openings.filter(o=>o.wall!==selected);commit(p,null);}
function duplicate(){const info=entity();if(info?.key!=='furniture')return;const p=clone(project),f={...info.value,id:uid(),x:info.value.x+25,y:info.value.y+25,name:info.value.name+' · kopia'};p.furniture.push(f);commit(p,f.id);}
let space=false;
$('plan').addEventListener('contextmenu',e=>e.preventDefault());
$('plan').addEventListener('pointerdown',e=>{
 if(mode!=='2d')return;finishEdit();const p=point(e);if(e.button===2||e.button===1||space){e.preventDefault();drag={type:'pan',point:p,view:{...view}};$('plan').setPointerCapture(e.pointerId);return;}
 if(e.button!==0)return;
 if(tool==='select'){
  const target=e.target.closest('[data-id]');if(!target){select(null);return;}
  selected=target.dataset.id;const info=entity();if(!info)return;const handle=target.dataset.handle;drag={type:handle==='rotate'?'rotate':'move',id:selected,key:info.key,handle,point:p,before:clone(project),moved:false};render();$('plan').setPointerCapture(e.pointerId);return;
 }
 const pt=snapPoint(p,e.shiftKey);
 if(tool.startsWith('furniture:')){const next=clone(project);let f=makeFurniture(tool.split(':')[1],pt.x,pt.y);f=snapFurniture(project,f,gridStep,8,magnet);next.furniture.push(f);commit(next,f.id);setTool('select');showTab('properties');return;}
 if(tool==='door'||tool==='window'){
  const match=project.walls.map(w=>({w,...projectOnWall(p,w)})).sort((a,b)=>a.distance-b.distance)[0];
  if(!match||match.distance>Math.max(15,view.w/$('stage').clientWidth*20)){toast('Kliknij bliżej ściany.',true);return;}
  const width=tool==='door'?80:120,l=wallLength(match.w);if(l<width){toast('Ta ściana jest za krótka na otwór. Wybierz dłuższą ścianę.',true);return;}
  const o={id:uid(),name:tool==='door'?'Drzwi':'Okno',kind:tool,wall:match.w.id,t:Math.max(width/2/l,Math.min(1-width/2/l,match.t)),width,height:tool==='door'?205:140,sill:tool==='door'?0:90,side:1,hinge:1};
  const next=clone(project);next.openings.push(o);commit(next,o.id);if(entity(o.id)){setTool('select');showTab('properties');}return;
 }
 if(tool==='label'){const next=clone(project),l={id:uid(),name:'POMIESZCZENIE',x:pt.x,y:pt.y};next.labels.push(l);commit(next,l.id);setTool('select');showTab('properties');return;}
 if(!pendingPoint){pendingPoint=pt;previewPoint=pt;draw();return;}
 const start=pendingPoint;if(dist(start,pt)<(tool==='measure'?.1:10)){toast('Wybierz drugi punkt dalej od początku.',true);return;}
 const next=clone(project);let id=null;
 if(tool==='wall'){const w=makeWall(start,pt);next.walls.push(w);id=w.id;}
 else if(tool==='measure'){const m={id:uid(),name:'Pomiar',a:start,b:pt};next.measurements.push(m);id=m.id;}
 else if(tool==='room'){
  if(Math.abs(start.x-pt.x)<30||Math.abs(start.y-pt.y)<30){toast('Obrys musi mieć co najmniej 30 × 30 cm.',true);return;}
  const x=Math.min(start.x,pt.x),y=Math.min(start.y,pt.y),w=Math.abs(pt.x-start.x),d=Math.abs(pt.y-start.y),corners=[{x,y},{x:x+w,y},{x:x+w,y:y+d},{x,y:y+d}];
  for(let i=0;i<4;i++){const a=corners[i],b=corners[(i+1)%4];if(!next.walls.some(v=>(dist(v.a,a)<.1&&dist(v.b,b)<.1)||(dist(v.b,a)<.1&&dist(v.a,b)<.1)))next.walls.push(makeWall(a,b));}
  const label={id:uid(),name:'POKÓJ',x:x+w/2,y:y+d/2};next.labels.push(label);id=label.id;
 }
 pendingPoint=null;previewPoint=null;commit(next,id);if(tool!=='wall')setTool('select');
});
$('plan').addEventListener('pointermove',e=>{
 if(mode!=='2d')return;const p=point(e);$('cursor').textContent=`X ${fmt(p.x)} · Y ${fmt(p.y)} cm`;
 if(pendingPoint){previewPoint=snapPoint(p,e.shiftKey);draw();return;}if(!drag)return;
 if(drag.type==='pan'){const b=$('stage').getBoundingClientRect(); // Screen deltas are stable while changing the viewBox.
  if(!drag.screen){drag.screen={x:e.clientX,y:e.clientY};return;}
  view.x-=(e.clientX-drag.screen.x)*view.w/b.width;view.y-=(e.clientY-drag.screen.y)*view.h/b.height;drag.screen={x:e.clientX,y:e.clientY};applyView();return;
 }
 const dx=p.x-drag.point.x,dy=p.y-drag.point.y;if(Math.hypot(dx,dy)<.2&&!drag.moved)return;drag.moved=true;
 const next=clone(drag.before),info=entity(drag.id,next),v=info.value,original=entity(drag.id,drag.before).value;
 if(drag.type==='rotate'){let angle=Math.atan2(p.y-v.y,p.x-v.x)*180/Math.PI+90;const step=e.shiftKey?1:15;v.angle=Math.round(angle/step)*step;}
 else if(info.key==='furniture'){Object.assign(v,snapFurniture(next,{...v,x:original.x+dx,y:original.y+dy},gridStep,8*view.w/$('stage').clientWidth,magnet));}
 else if(info.key==='walls'||info.key==='measurements'){
  if(drag.handle){const end=snapPoint(p);v[drag.handle]={x:end.x,y:end.y};}
  else {const sx=Math.round(dx/gridStep)*gridStep,sy=Math.round(dy/gridStep)*gridStep;v.a={x:original.a.x+sx,y:original.a.y+sy};v.b={x:original.b.x+sx,y:original.b.y+sy};}
 }
 else if(info.key==='openings'){const w=next.walls.find(w=>w.id===v.wall),l=wallLength(w),pr=projectOnWall(p,w);const along=Math.round(pr.t*l/gridStep)*gridStep;v.t=Math.max(v.width/2/l,Math.min(1-v.width/2/l,along/l));}
 else if(info.key==='labels'){v.x=Math.round((original.x+dx)/gridStep)*gridStep;v.y=Math.round((original.y+dy)/gridStep)*gridStep;}
 try{project=validatePlan(next);render(true);updateSummary();}catch{/* Keep last valid position when an opening no longer fits its wall. */}
});
function endDrag(){if(!drag)return;const old=drag;drag=null;if(old.before&&JSON.stringify(old.before)!==JSON.stringify(project)){push(old.before);persist();}render();}
$('plan').addEventListener('pointerup',endDrag);$('plan').addEventListener('pointercancel',()=>{cancelGesture();});
$('plan').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.1:.9,point(e));},{passive:false});
async function setView(next){finishEdit();mode=next;pendingPoint=null;previewPoint=null;$('plan').toggleAttribute('hidden',next==='3d');$('three').hidden=next!=='3d';$('low-wall-label').hidden=next!=='3d';$('view-2d').classList.toggle('active',next==='2d');$('view-3d').classList.toggle('active',next==='3d');syncTools();
 if(next==='3d'){
  if(!view3d){try{const {RoomView3D}=await import('./view3d.js?v=2026-09-30');if(view3d||mode!=='3d')return;$('three').replaceChildren();view3d=new RoomView3D($('three'),id=>{select(id);showTab('properties');});view3d.update(project,selected,issues,{lowWalls:$('low-walls').checked,zones:showZones});view3d.fit();}catch(error){$('three').innerHTML='<p id="three-error">Podgląd 3D nie mógł się uruchomić. Rzut 2D, edycja i zapis pozostają dostępne. Sprawdź obsługę WebGL w przeglądarce.</p>';console.error(error);}}
  else{view3d.resize();view3d.update(project,selected,issues,{lowWalls:$('low-walls').checked,zones:showZones});}
 }else {applyView();draw();}
}
function download(data,mime,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type:mime}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const filename=ext=>(project.name||'plan').replace(/[^\p{L}\p{N} _-]/gu,'').trim().replace(/ +/g,'-')+ext;
$('save-project').onclick=()=>{finishEdit();download(JSON.stringify(project,null,2),'application/json',filename('.pomieszczenia.json'));persist();toast('Pobrano plik projektu. Możesz otworzyć go na innym urządzeniu.');};
$('open-project').onclick=()=>$('file-input').click();$('file-input').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>3_000_000)throw Error('Plik jest za duży (maks. 3 MB).');const p=validatePlan(JSON.parse(await file.text()));commit(p,null);fit();toast('Wczytano projekt. Cofnij przywraca poprzedni.');}catch(error){toast(error.message,true);}};
$('export-plan').onclick=()=>{finishEdit();pendingPoint=null;const old=selected;selected=null;draw();const b=planBounds(),s=$('plan').cloneNode(true);s.removeAttribute('id');s.removeAttribute('class');s.removeAttribute('hidden');s.setAttribute('xmlns','http://www.w3.org/2000/svg');s.setAttribute('viewBox',`${b.minX-70} ${b.minY-70} ${b.maxX-b.minX+140} ${b.maxY-b.minY+140}`);s.setAttribute('width','1400');s.setAttribute('height',String(Math.round(1400*(b.maxY-b.minY+140)/(b.maxX-b.minX+140))));download(new XMLSerializer().serializeToString(s),'image/svg+xml',filename('.svg'));selected=old;draw();};
$('print-plan').onclick=async()=>{await setView('2d');fit();window.print();};
let replacement=null;function askReplace(kind){replacement=kind;$('dialog-title').textContent=kind==='demo'?'Wstawić przykładowe mieszkanie?':'Utworzyć pusty plan?';$('replace-dialog').showModal();}
$('new-plan').onclick=()=>askReplace('empty');$('demo-plan').onclick=()=>askReplace('demo');$('dialog-cancel').onclick=()=>$('replace-dialog').close();$('dialog-ok').onclick=()=>{commit(replacement==='demo'?demoPlan():blankPlan(),null);$('replace-dialog').close();setTool('select');fit();};
$('project-name').addEventListener('focus',()=>{finishEdit();edit={before:clone(project),input:$('project-name')};});$('project-name').addEventListener('input',()=>{project.name=$('project-name').value; $('canvas-title').textContent=project.name.toUpperCase();});$('project-name').addEventListener('blur',()=>{if(!project.name.trim())project.name='Mój plan';finishEdit();$('project-name').value=project.name;});
$('undo').onclick=undo;$('redo').onclick=redo;$('select-tool').onclick=()=>setTool('select');$('fit').onclick=fit;$('view-2d').onclick=()=>setView('2d');$('view-3d').onclick=()=>setView('3d');$('low-walls').onchange=()=>render();
$('magnet').onclick=()=>{magnet=!magnet;$('magnet').classList.toggle('active',magnet);$('magnet').setAttribute('aria-pressed',magnet);};$('grid-step').onchange=e=>gridStep=Number(e.target.value);$('precision').onchange=e=>{finishEdit();precision=Number(e.target.value);render();};$('show-dimensions').onchange=e=>{showDimensions=e.target.checked;draw();};$('show-zones').onchange=e=>{showZones=e.target.checked;render();};
$('zoom-out').onclick=()=>zoom(1.2);$('zoom-in').onclick=()=>zoom(1/1.2);$('tab-properties').onclick=()=>showTab('properties');$('tab-check').onclick=()=>showTab('checks');
$('catalog-search').oninput=renderCatalog;document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(v=>v.classList.toggle('active',v===b));renderCatalog();});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$('show-library').onclick=()=>$('library').classList.toggle('open');$('show-inspector').onclick=()=>$('inspector').classList.toggle('open');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));
window.addEventListener('keydown',e=>{const isInput=e.target.matches('input,select,textarea');if(e.key==='Escape'){cancelGesture();setTool('select');if(isInput)e.target.blur();return;}if(isInput||$('replace-dialog').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return;}if(e.code==='Space'){space=true;e.preventDefault();}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();removeSelected();}if(e.key.toLowerCase()==='r'&&entity()?.key==='furniture')updateSelected(f=>{f.angle=(f.angle+90)%360;});
 if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&entity()?.key==='furniture'){e.preventDefault();const step=gridStep*(e.shiftKey?10:1);updateSelected(f=>{if(e.key==='ArrowLeft')f.x-=step;if(e.key==='ArrowRight')f.x+=step;if(e.key==='ArrowUp')f.y-=step;if(e.key==='ArrowDown')f.y+=step;});}});
window.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;endDrag();finishEdit();});window.addEventListener('beforeunload',e=>{finishEdit();if(!stored){e.preventDefault();e.returnValue='';}});
let resizeTimer;new ResizeObserver(()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const b=$('stage').getBoundingClientRect();if(b.width&&b.height){const h=view.w*b.height/b.width;view.y+=(view.h-h)/2;view.h=h;applyView();}},60);}).observe($('stage'));
renderCatalog();render();requestAnimationFrame(fit);
